{"name": "Account creation", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '#firstname')).has text tester\nReason: AssertionError: actual text: \nScreenshot: file:///root/.selene/screenshots/1580815200904/1580815200905.png\nPageSource: file:///root/.selene/screenshots/1580815200904/1580815200905.html\n\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/steps.py\", line 59, in step_impl\n    s(\"#firstname\").should(have.text(FIRST_NAME))\n  File \"/usr/local/lib/python3.8/site-packages/selene/core/entity.py\", line 294, in should\n    super().should(condition)\n  File \"/usr/local/lib/python3.8/site-packages/selene/core/entity.py\", line 121, in should\n    self.wait.for_(condition)\n  File \"/usr/local/lib/python3.8/site-packages/selene/core/wait.py\", line 100, in for_\n    raise self._hook_failure(failure)\n"}, "steps": [{"name": "Given I am in Sign In page", "status": "passed", "start": 1580815202061, "stop": 1580815206110}, {"name": "When I enter email in Create New Account section", "status": "passed", "start": 1580815206110, "stop": 1580815207967}, {"name": "And I enter valid account details", "status": "passed", "start": 1580815207967, "stop": 1580815209220}, {"name": "And click on Register button", "status": "passed", "start": 1580815209220, "stop": 1580815211755}, {"name": "And My Account page is opened", "status": "passed", "start": 1580815211755, "stop": 1580815211818}, {"name": "And I click on My Personal Information button", "status": "passed", "start": 1580815211818, "stop": 1580815213409}, {"name": "Then Your Personal Information page is opened", "status": "passed", "start": 1580815213409, "stop": 1580815213444}, {"name": "And correct personal information is displayed", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '#firstname')).has text tester\nReason: AssertionError: actual text: \nScreenshot: file:///root/.selene/screenshots/1580815200904/1580815200905.png\nPageSource: file:///root/.selene/screenshots/1580815200904/1580815200905.html\n\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/steps.py\", line 59, in step_impl\n    s(\"#firstname\").should(have.text(FIRST_NAME))\n  File \"/usr/local/lib/python3.8/site-packages/selene/core/entity.py\", line 294, in should\n    super().should(condition)\n  File \"/usr/local/lib/python3.8/site-packages/selene/core/entity.py\", line 121, in should\n    self.wait.for_(condition)\n  File \"/usr/local/lib/python3.8/site-packages/selene/core/wait.py\", line 100, in for_\n    raise self._hook_failure(failure)\n"}, "start": 1580815213444, "stop": 1580815217550}], "start": 1580815202061, "stop": 1580815217551, "uuid": "3da99eb4-ba37-48f3-8ac2-1cbab63930de", "historyId": "65deff046e9e25a740783ffb86da98a7", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "automationpractice"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}